name: test-nodejs-app-workflow
on: [ push, pull_request ]
jobs: 
  test_job:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: GitHub Metadata
        run: echo "{{toJSON(github)}}"
